name: Bannersbane
version: '${version}'
main: com.thatguyjack.bannerfallCharters.BannerfallCharters
api-version: '1.21.11'
authors: [ThatGuyJack]
description: Custom player powers and Bannerfall modifications

depend:
  - Bannerfall
  - DungeonFall
  - Scheduler
  - ProtocolLib

commands:
  bannersbane:
    description: Main command for Bannersbane.
    usage: /bannersbane
    permission: bannersbane.admin
    aliases:
      - bb
      - bsbane
      - charter

permissions:
  bannersbane.admin:
    description: Allows use of Bannersbane admin commands.
    default: op

  bannerfallcharters.admin:
    description: Legacy permission for old Bannerfall Charters command access.
    default: op
